process_slides_task:
  description: >
    Process and clean slide content for speaker: {speaker}
    
    RAW SLIDES CONTENT:
    {slides_raw}
    
    QR CODES FOUND:
    {qr_codes}
    
    VISUAL ELEMENTS:
    {visual_elements}
    
    SOURCE FILE: {pdf_path}
    
    CODA VALIDATION DATA (source of truth from database):
    - Speaker: "{coda_speaker}"
    - Affiliation: "{coda_affiliation}" 
    - Title: "{coda_title}"
    
    CRITICAL SPEAKER VALIDATION:
    Before processing slides, examine the FIRST SLIDE to validate speaker information against Coda data.
    
    VALIDATION RULES:
    1. Speaker name validation:
       - Minor variations OK: Robert -> Bob, Tom -> Thomas, Dr. John -> John
       - Major changes NOT OK: Adam Gleave -> Adam Kalai, Ben Bucknall -> Ben Cottier
       - If acceptable variation: prefix updated name with "* "
       - If major mismatch: prefix with "** " and add banner (see below)
    
    2. Affiliation validation:
       - Update if different from Coda, prefix with "* "
    
    3. Title validation:
       - Update if different from Coda, prefix with "* "
    
    4. Major mismatch handling:
       - If there's a major difference suggesting wrong slides, DON'T update any fields
       - Prefix speaker name with "** " 
       - Add banner to first line of cleaned_slides: "[*** BEWARE: MISMATCH BETWEEN SPEAKER & SLIDES ***]"
    
    Your processing should:
    - PRESERVE ALL ORIGINAL SLIDE TEXT VERBATIM - do not summarize, paraphrase, or rewrite
    - Clean and structure the provided slide content while keeping exact wording
    - Preserve all technical terminology, formulas, and acronyms exactly as written
    - Maintain the original slide structure and organization
    - SKIP decorative visual elements: logos, profile photos, generic images unless they contain important content
    - Mark important visual elements only: [chart: description] for data charts, [diagram: description] for technical diagrams
    - Include QR codes from the QR CODES FOUND section as verified resources
    - If any slides appear missing from the raw content, note this in processing_notes
    - Extract and catalog MAIN WORK resources only (not comprehensive bibliography):
      * QR code URLs (high priority - intentionally shared by speaker)
      * Primary research paper being presented (usually in title/main slides)
      * Key datasets or codebases that are the focus of the talk
      * SKIP: speaker homepages, institution links, extensive reference lists, related work citations
    - Identify slide titles, main sections, and organizational structure
    
  expected_output: >
    {
      "cleaned_slides": "VERBATIM slide content with exact original text preserved, visual elements marked as [img: alt], [chart: alt], etc. Include banner if major mismatch detected.",
      "slide_structure": {
        "title": "Presentation title from slides (updated if validation passed)",
        "main_sections": ["Section 1", "Section 2", "Section 3"],
        "slide_count": "Number of slides processed"
      },
      "speaker_validation": {
        "slide_speaker": "Speaker name found on first slide",
        "slide_affiliation": "Affiliation found on first slide", 
        "slide_title": "Title found on first slide",
        "validation_result": "valid|minor_differences|major_mismatch",
        "updates_made": {
          "speaker_updated": "Updated speaker name with prefix if changed",
          "affiliation_updated": "Updated affiliation with prefix if changed",
          "title_updated": "Updated title with prefix if changed"
        },
        "validation_notes": "Explanation of validation decisions and any issues"
      },
      "resources_found": [
        {
          "type": "qr_code|url|paper|arxiv|doi|dataset|github|text_reference",
          "title": "Resource title or description", 
          "url": "Direct URL if available (especially for QR codes)",
          "reference": "Original reference as found in slides or QR code",
          "context": "Brief context where it was mentioned",
          "source": "qr_code|slide_text"
        }
      ],
      "technical_terms": ["List of key technical terms and acronyms found"],
      "processing_notes": "Any issues encountered during processing, including speaker validation"
    }
  agent: slide_processor_agent

process_transcript_task:
  description: >
    Clean and format transcript for speaker: {speaker}
    
    RAW TRANSCRIPT (SRT format from AssemblyAI):
    {transcript_raw}
    
    SOURCE: {transcript_source}
    SLIDES CONTEXT (from previous task for technical accuracy):
    Use the slides content from the previous task to ensure name spelling and technical terms are correct.
    
    ---
    TRANSCRIPT STYLE GUIDE:
    {style_transcript}
    ---
    
    CRITICAL REQUIREMENTS - FAILURE TO FOLLOW WILL RESULT IN REJECTION:
    1. WORD COUNT VALIDATION: Your output must contain 95-105% of the original word count
    2. VERBATIM PRESERVATION: Keep EVERY SINGLE WORD from the original transcript
    3. ONLY ALLOWED CHANGES: Fix spelling/terminology using style guide, add paragraph breaks
    4. FORBIDDEN ACTIONS: Do NOT remove, summarize, shorten, or paraphrase ANY content
    5. FORBIDDEN ACTIONS: Do NOT add section headers, titles, or structural elements
    
    Processing steps:
    1. Extract text from SRT format (ignore timestamps - preserved automatically)
    2. Count words in original text and log this number
    3. Apply transcript style guide corrections ONLY for spelling/terminology
    4. Use slide context for technical term accuracy
    5. Organize into paragraphs (50-100 words) at natural topic transitions
    6. Count words in final output - MUST be within 95-105% of original count
    7. If word count drops below 95%, you have failed the task - try again
    
  expected_output: >
    {
      "transcript_formatted": "COMPLETE verbatim transcript text with ALL original words preserved, only corrected technical terms, organized into readable paragraphs, no headers or topic titles - WORD COUNT MUST BE NEARLY IDENTICAL TO ORIGINAL",
      "transcript_stats": {
        "original_word_count": "REQUIRED: Word count from original SRT text",
        "output_word_count": "REQUIRED: Word count in transcript_formatted",
        "word_count_percentage": "REQUIRED: (output/original)*100 - MUST be 95-105%",
        "paragraph_count": "Number of paragraphs created",
        "duration_minutes": "Video duration if available"
      },
      "cleaning_notes": "Details about spelling/terminology corrections made using slide context",
      "processing_status": "success|partial|failed - FAIL if word count below 95%"
    }
  agent: transcript_processor_agent
  context:
    - process_slides_task

research_resources_task:
  description: >
    Research and find actual URLs for the PRIMARY resources identified in slides (not comprehensive bibliography).
    
    Use only the MAIN WORK resources from the previous slide processing task - typically 1-2 resources max.
    
    Your research should focus on:
    - QR code URLs (high priority):
      * These URLs are already verified - do NOT search for them
      * Visit the URL to get the page title and determine resource type (paper, codebase, website, dataset)
      * Extract basic info: type, title, url (keep original QR URL)
    - Primary research paper being presented:
      * Search using queries like "[paper title] [conference] [year]", "[paper title] arXiv"  
      * Look for arXiv preprints, official conference proceedings, ACM Digital Library, IEEE Xplore
      * Try variations with author names + key terms from talk title
    - Key datasets/codebases that are the main focus:
      * Only if they are central to the work being presented
    
    STRICT EXCLUSIONS:
    - Do NOT search for social media posts
    - Do NOT include speaker homepages or institutional links
    - Do NOT include related work or comprehensive reference lists
    - Do NOT include background/citation papers
    
    Expected result: 0-2 resources typically, max 4 for multi-paper presentations
    Format: simple text format, NO emojis, one resource per line
    
  expected_output: >
    {
      "researched_resources": [
        {
          "original_reference": "Reference as found in slides",
          "title": "Full paper/resource title",
          "url": "Actual URL if found, or 'NOT_FOUND'",
          "citation": "Complete citation information",
          "source": "Where URL was found (arXiv, ACM, IEEE, etc.)",
          "status": "found|partial|not_found",
          "notes": "Additional information or search attempts"
        }
      ],
      "resources_formatted": "Formatted string ready for Coda Resources column",
      "research_summary": {
        "total_resources": "Number of resources processed",
        "urls_found": "Number of actual URLs found",
        "citations_only": "Number with citation info but no URL"
      }
    }
  agent: resource_researcher_agent
  context:
    - process_slides_task

analyze_transcript_task:
  description: >
    Analyze the CLEANED transcript from the transcript processing task to extract core findings, technical details, key insights, and organizational structure.
    This analysis should use the cleaned, formatted transcript (not the raw transcript) that has been processed and refined by the transcript processor.
    
    INSTRUCTIONS:
    1. Look at the transcript processing task output (if available) and extract the "transcript_formatted" content
    2. If no cleaned transcript is available from the transcript processing task, return an analysis indicating no transcript is available
    3. Only perform detailed analysis if substantial cleaned transcript content is available
    
    SPEAKER INFO:
    - Speaker: {speaker}
    - Affiliation: {coda_affiliation}
    
    Your analysis should (using the cleaned transcript from context):
    - Identify the main thesis and supporting arguments
    - Extract the speaker's organizational pattern and talk structure
    - Capture the speaker's section titles, main points, and flow
    - Extract specific technical details, numbers, and metrics
    - Find surprising or counterintuitive claims
    - Collect impactful direct quotes from the speaker
    - Highlight key findings for both technical and non-technical audiences
    
  expected_output: >
    {
      "analysis_status": "completed|no_transcript_available",
      "speaker": "{speaker} ({coda_affiliation})",
      "core_thesis": "Main argument in 1 sentence OR 'No transcript available'",
      "key_findings": ["Finding 1", "Finding 2", "Finding 3"] OR [],
      "talk_outline": {
        "structure_type": "Describe the speaker's organizational pattern OR 'No transcript available'",
        "main_points": [
          {"point": "First main point/section title", "details": "Key content and supporting details"},
          {"point": "Second main point/section title", "details": "Key content and supporting details"}
        ] OR []
      },
      "technical_details": {"metrics": ["...", "..."], "methods": ["...", "..."], "numbers": ["..."] OR "Not applicable - policy/strategic talk"} OR {},
      "surprising_claims": ["Counterintuitive insight 1", "Counterintuitive insight 2"] OR [],
      "impactful_quotes": ["Direct quote 1", "Direct quote 2"] OR []
    }
  agent: transcript_analyzer_agent
  context:
    - process_transcript_task

final_assembly_task:
  description: >
    Assemble all processed content and prepare final outputs for Coda database update.
    
    Extract the ACTUAL content from previous tasks:
    - Slides: Use "cleaned_slides" content from slide processing task (if not skipped)
    - Resources: Use "resources_formatted" string from resource research task  
    - SRT: Use "transcript_srt" content (with timestamps) from transcript processing task (if not skipped)
    - Transcript: Use "transcript_formatted" content (clean paragraphs) from transcript processing task (if not skipped)
    - Analysis: Convert transcript analysis JSON to markdown format for Coda storage (if transcript was processed)
    - Speaker Validation: Apply validated speaker information updates from slide processing
    - Generate processing summary for "Webhook progress" column
    - Set "Webhook status" to "Done"
    
    TRANSCRIPT ANALYSIS FORMATTING:
    If transcript analysis was completed, convert the JSON output to readable markdown format:
    - Core Thesis: Display as "## Core Thesis" section
    - Key Findings: Display as "## Key Findings" with bullet list
    - Talk Outline: Display as "## Talk Structure" with structured format
    - Technical Details: Display as "## Technical Details" (if applicable)
    - Surprising Claims: Display as "## Key Insights" with bullet list
    - Impactful Quotes: Display as "## Notable Quotes" with quote formatting
    
    CRITICAL SPEAKER VALIDATION HANDLING:
    From the slide processing task "speaker_validation" section:
    1. If validation_result is "valid" or "minor_differences", apply updates to Coda:
       - If "speaker_updated" exists: update "Speaker" column with the prefixed value
       - If "affiliation_updated" exists: update "Affiliation" column with the prefixed value  
       - If "title_updated" exists: update "Title" column with the prefixed value
    2. If validation_result is "major_mismatch", do NOT update speaker fields
    3. Include validation details in "Webhook progress" for transparency
    
    IMPORTANT: For any skipped content, do NOT include those fields in coda_updates.
    Only include fields for content that was actually processed (not skipped).
    
  expected_output: >
    {
      "coda_updates": {
        "Slides": "Complete slides content with visual elements marked",
        "Resources": "Formatted resource list ready for Coda", 
        "SRT": "Full SRT transcript with timestamps",
        "Transcript": "Clean formatted transcript paragraphs",
        "Analysis": "Transcript analysis in markdown format (only if transcript was processed)",
        "Speaker": "Updated speaker name (only if validated and updated)",
        "Affiliation": "Updated affiliation (only if validated and updated)",
        "Title": "Updated title (only if validated and updated)",
        "Webhook progress": "Processing completed successfully: X slides, Y resources, Z words. Analysis: [included/skipped]. Speaker validation: [status and details]",
        "Webhook status": "Done"
      },
      "processing_summary": {
        "slides_processed": "Number of slides",
        "resources_found": "Number of resources", 
        "transcript_length": "Word count",
        "speaker_validation": "Validation result and updates applied",
        "total_processing_time": "Processing time"
      }
    }
  agent: slide_processor_agent
  context:
    - process_slides_task
    - process_transcript_task  
    - research_resources_task
    - analyze_transcript_task