process_slides_task:
  description: >
    Process and clean slide content for speaker: {speaker}
    
    EXISTING CONTENT CHECK: Slides already exist in Coda = {slides_already_exist}
    
    If slides_already_exist = True, SKIP slide processing entirely and return:
    {{"cleaned_slides": "SKIPPED - Slides already exist in Coda", "processing_notes": "Skipped slide processing - content already exists"}}
    
    Otherwise, process the slides normally:
    
    RAW SLIDES CONTENT:
    {slides_raw}
    
    QR CODES FOUND:
    {qr_codes}
    
    VISUAL ELEMENTS:
    {visual_elements}
    
    SOURCE FILE: {pdf_path}
    
    Your processing should:
    - PRESERVE ALL ORIGINAL SLIDE TEXT VERBATIM - do not summarize, paraphrase, or rewrite
    - Clean and structure the provided slide content while keeping exact wording
    - Preserve all technical terminology, formulas, and acronyms exactly as written
    - Maintain the original slide structure and organization
    - SKIP decorative visual elements: logos, profile photos, generic images unless they contain important content
    - Mark important visual elements only: [chart: description] for data charts, [diagram: description] for technical diagrams
    - Include QR codes from the QR CODES FOUND section as verified resources
    - If any slides appear missing from the raw content, note this in processing_notes
    - Extract and catalog ALL resources mentioned, including:
      * QR code URLs (already verified - add directly to resources)
      * Direct URLs (http/https links) from text
      * Research paper titles with conference/journal info (e.g., "MasterKey (NDSS'24)")
      * arXiv references (e.g., "arXiv:2502.12202")
      * DOI references
      * Dataset mentions
      * GitHub repositories
    - Identify slide titles, main sections, and organizational structure
    
  expected_output: >
    {
      "cleaned_slides": "VERBATIM slide content with exact original text preserved, visual elements marked as [img: alt], [chart: alt], etc.",
      "slide_structure": {
        "title": "Presentation title",
        "main_sections": ["Section 1", "Section 2", "Section 3"],
        "slide_count": "Number of slides processed"
      },
      "resources_found": [
        {
          "type": "qr_code|url|paper|arxiv|doi|dataset|github|text_reference",
          "title": "Resource title or description", 
          "url": "Direct URL if available (especially for QR codes)",
          "reference": "Original reference as found in slides or QR code",
          "context": "Brief context where it was mentioned",
          "source": "qr_code|slide_text"
        }
      ],
      "technical_terms": ["List of key technical terms and acronyms found"],
      "processing_notes": "Any issues encountered during processing"
    }
  agent: slide_processor_agent

process_transcript_task:
  description: >
    Clean and format transcript for speaker: {speaker}
    
    EXISTING CONTENT CHECK: SRT already exists in Coda = {srt_already_exists}
    
    If srt_already_exists = True, SKIP transcript processing entirely and return:
    {{"transcript_formatted": "SKIPPED - SRT already exists in Coda", "processing_status": "skipped", "cleaning_notes": "Skipped transcript processing - content already exists"}}
    
    Otherwise, process the transcript normally:
    
    RAW TRANSCRIPT (SRT format from AssemblyAI):
    {transcript_raw}
    
    SOURCE: {transcript_source}
    SLIDES CONTEXT (from previous task for technical accuracy):
    Use the slides content from the previous task to ensure name spelling and technical terms are correct.
    
    ---
    TRANSCRIPT STYLE GUIDE:
    {style_transcript}
    ---
    
    CRITICAL REQUIREMENTS - FAILURE TO FOLLOW WILL RESULT IN REJECTION:
    1. WORD COUNT VALIDATION: Your output must contain 95-105% of the original word count
    2. VERBATIM PRESERVATION: Keep EVERY SINGLE WORD from the original transcript
    3. ONLY ALLOWED CHANGES: Fix spelling/terminology using style guide, add paragraph breaks
    4. FORBIDDEN ACTIONS: Do NOT remove, summarize, shorten, or paraphrase ANY content
    5. FORBIDDEN ACTIONS: Do NOT add section headers, titles, or structural elements
    
    Processing steps:
    1. Extract text from SRT format (ignore timestamps - preserved automatically)
    2. Count words in original text and log this number
    3. Apply transcript style guide corrections ONLY for spelling/terminology
    4. Use slide context for technical term accuracy
    5. Organize into paragraphs (50-100 words) at natural topic transitions
    6. Count words in final output - MUST be within 95-105% of original count
    7. If word count drops below 95%, you have failed the task - try again
    
  expected_output: >
    {
      "transcript_formatted": "COMPLETE verbatim transcript text with ALL original words preserved, only corrected technical terms, organized into readable paragraphs, no headers or topic titles - WORD COUNT MUST BE NEARLY IDENTICAL TO ORIGINAL",
      "transcript_stats": {
        "original_word_count": "REQUIRED: Word count from original SRT text",
        "output_word_count": "REQUIRED: Word count in transcript_formatted",
        "word_count_percentage": "REQUIRED: (output/original)*100 - MUST be 95-105%",
        "paragraph_count": "Number of paragraphs created",
        "duration_minutes": "Video duration if available"
      },
      "cleaning_notes": "Details about spelling/terminology corrections made using slide context",
      "processing_status": "success|partial|failed - FAIL if word count below 95%"
    }
  agent: transcript_processor_agent
  context:
    - process_slides_task

research_resources_task:
  description: >
    Research and find actual URLs for academic papers and resources identified in slides.
    
    Use the resources found in the previous slide processing task to research actual URLs and complete citations.
    
    Your research should:
    - For QR code URLs (type: "qr_code"):
      * These URLs are already verified - do NOT search for them
      * Visit the URL to get the page title and determine resource type (paper, codebase, website, dataset)
      * Extract basic info: type, title, url (keep original QR URL)
    - For text references without URLs:
      * Search using queries like "MasterKey NDSS 2024 paper", "MasterKey NDSS'24 arXiv"  
      * Look for arXiv preprints, official conference proceedings, ACM Digital Library, IEEE Xplore
      * Try variations with author names from slides + key terms
      * Search academic databases: "site:arxiv.org", "site:dl.acm.org", "site:ieeexplore.ieee.org"
    - Search for existing social media posts:
      * Look for X/Twitter posts: "[speaker name] [research topic] site:twitter.com" or "site:x.com"
      * Look for LinkedIn posts: "[author name] [paper title] site:linkedin.com"
      * Find posts by the speaker or their institution about this research for potential retweet/repost
    - For all resources, provide simple format:
      * type: paper, codebase, website, dataset, etc.
      * title: Clean page/paper title  
      * url: Working URL (QR code URL for QR resources, found URL for searched resources)
    - Prioritize official/authoritative sources over mirrors
    - Format results for Coda "Resources" column: simple text format, NO emojis or icons, one resource per line
    - Focus on main paper from QR codes, skip institution/company links unless directly relevant
    
  expected_output: >
    {
      "researched_resources": [
        {
          "original_reference": "Reference as found in slides",
          "title": "Full paper/resource title",
          "url": "Actual URL if found, or 'NOT_FOUND'",
          "citation": "Complete citation information",
          "source": "Where URL was found (arXiv, ACM, IEEE, etc.)",
          "status": "found|partial|not_found",
          "notes": "Additional information or search attempts"
        }
      ],
      "resources_formatted": "Formatted string ready for Coda Resources column",
      "research_summary": {
        "total_resources": "Number of resources processed",
        "urls_found": "Number of actual URLs found",
        "citations_only": "Number with citation info but no URL"
      }
    }
  agent: resource_researcher_agent
  context:
    - process_slides_task

final_assembly_task:
  description: >
    Assemble all processed content and prepare final outputs for Coda database update.
    
    Extract the ACTUAL content from previous tasks:
    - Slides: Use "cleaned_slides" content from slide processing task (if not skipped)
    - Resources: Use "resources_formatted" string from resource research task  
    - SRT: Use "transcript_srt" content (with timestamps) from transcript processing task (if not skipped)
    - Transcript: Use "transcript_formatted" content (clean paragraphs) from transcript processing task (if not skipped)
    - Generate processing summary for "Webhook progress" column
    - Set "Webhook status" to "Done"
    
    IMPORTANT: For any skipped content, do NOT include those fields in coda_updates.
    Only include fields for content that was actually processed (not skipped).
    
  expected_output: >
    {
      "coda_updates": {
        "Slides": "Complete slides content with visual elements marked",
        "Resources": "Formatted resource list ready for Coda", 
        "SRT": "Full SRT transcript with timestamps",
        "Transcript": "Clean formatted transcript paragraphs",
        "Webhook progress": "Processing completed successfully: X slides, Y resources, Z words",
        "Webhook status": "Done"
      },
      "processing_summary": {
        "slides_processed": "Number of slides",
        "resources_found": "Number of resources", 
        "transcript_length": "Word count",
        "total_processing_time": "Processing time"
      }
    }
  agent: slide_processor_agent
  context:
    - process_slides_task
    - process_transcript_task  
    - research_resources_task