process_slides_task:
  description: >
    Process and clean slide content for speaker: {speaker}
    
    RAW SLIDES CONTENT:
    {slides_raw}
    
    QR CODES FOUND:
    {qr_codes}
    
    VISUAL ELEMENTS:
    {visual_elements}
    
    SOURCE FILE: {pdf_path}
    
    Your processing should:
    - Clean and structure the provided slide content
    - Preserve all technical terminology, formulas, and acronyms exactly
    - Maintain the original slide structure and organization
    - Include QR codes from the QR CODES FOUND section as verified resources
    - Include visual elements descriptions in the cleaned content
    - Extract and catalog ALL resources mentioned, including:
      * QR code URLs (already verified - add directly to resources)
      * Direct URLs (http/https links) from text
      * Research paper titles with conference/journal info (e.g., "MasterKey (NDSS'24)")
      * arXiv references (e.g., "arXiv:2502.12202")
      * DOI references
      * Dataset mentions
      * GitHub repositories
      * Author/collaborator references
      * Institution names
    - Identify slide titles, main sections, and organizational structure
    
  expected_output: >
    {
      "cleaned_slides": "Full cleaned slide content with proper formatting",
      "slide_structure": {
        "title": "Presentation title",
        "main_sections": ["Section 1", "Section 2", "Section 3"],
        "slide_count": "Number of slides processed"
      },
      "resources_found": [
        {
          "type": "qr_code|url|paper|arxiv|doi|dataset|github|text_reference",
          "title": "Resource title or description", 
          "url": "Direct URL if available (especially for QR codes)",
          "reference": "Original reference as found in slides or QR code",
          "context": "Brief context where it was mentioned",
          "source": "qr_code|slide_text"
        }
      ],
      "technical_terms": ["List of key technical terms and acronyms found"],
      "processing_notes": "Any issues encountered during processing"
    }
  agent: slide_processor_agent

process_transcript_task:
  description: >
    Clean and format transcript for speaker: {speaker}
    
    RAW TRANSCRIPT (SRT format from AssemblyAI):
    {transcript_raw}
    
    SOURCE: {transcript_source}
    SLIDES CONTEXT (from previous task for technical accuracy):
    Use the slides content from the previous task to ensure name spelling and technical terms are correct.
    
    Your processing should:
    1. Extract the text content from the SRT transcript (ignore timestamps - they will be preserved automatically):
       - Extract just the spoken text from the SRT format
       - Use slide context to correct technical terminology, acronyms, and complex terms
       - Fix speaker names and affiliations to match slides
       - CRITICAL: Only fix spelling/terminology - do NOT change, add, or remove any words
    2. Create readable paragraph format with corrected text:
       - CRITICAL: Keep EVERY SINGLE WORD from the original transcript - do not remove, summarize, or shorten anything
       - Only make spelling/terminology corrections, never remove content
       - Organize the corrected text into natural paragraph breaks at topic transitions  
       - Group related sentences together
       - Create substantial paragraphs (50-100 words each)
       - DO NOT add section headers, titles, or structural elements not in original speech
    3. Output only the clean paragraph format - SRT will be reconstructed automatically with original timestamps
    
    CRITICAL: The word count should be nearly identical to the original. Focus only on text accuracy and paragraph formatting. Timestamps will be preserved automatically by the system.
    
  expected_output: >
    {
      "transcript_formatted": "COMPLETE verbatim transcript text with ALL original words preserved, only corrected technical terms, organized into readable paragraphs, no headers or topic titles - WORD COUNT SHOULD BE NEARLY IDENTICAL TO ORIGINAL",
      "transcript_stats": {
        "duration_minutes": "Actual video duration",
        "word_count": "Actual word count",
        "paragraph_count": "Actual number of paragraphs created"
      },
      "cleaning_notes": "Actual details about spelling/terminology corrections made using slide context",
      "processing_status": "success|partial|failed with actual details"
    }
  agent: transcript_processor_agent
  context:
    - process_slides_task

research_resources_task:
  description: >
    Research and find actual URLs for academic papers and resources identified in slides.
    
    Use the resources found in the previous slide processing task to research actual URLs and complete citations.
    
    Your research should:
    - For QR code URLs (type: "qr_code"):
      * These URLs are already verified - do NOT search for them
      * Visit the URL to get the page title and determine resource type (paper, codebase, website, dataset)
      * Extract basic info: type, title, url (keep original QR URL)
    - For text references without URLs:
      * Search using queries like "MasterKey NDSS 2024 paper", "MasterKey NDSS'24 arXiv"  
      * Look for arXiv preprints, official conference proceedings, ACM Digital Library, IEEE Xplore
      * Try variations with author names from slides + key terms
      * Search academic databases: "site:arxiv.org", "site:dl.acm.org", "site:ieeexplore.ieee.org"
    - For all resources, provide simple format:
      * type: paper, codebase, website, dataset, etc.
      * title: Clean page/paper title  
      * url: Working URL (QR code URL for QR resources, found URL for searched resources)
    - Prioritize official/authoritative sources over mirrors
    - Format results for easy integration into Coda "Resources" column
    
  expected_output: >
    {
      "researched_resources": [
        {
          "original_reference": "Reference as found in slides",
          "title": "Full paper/resource title",
          "url": "Actual URL if found, or 'NOT_FOUND'",
          "citation": "Complete citation information",
          "source": "Where URL was found (arXiv, ACM, IEEE, etc.)",
          "status": "found|partial|not_found",
          "notes": "Additional information or search attempts"
        }
      ],
      "resources_formatted": "Formatted string ready for Coda Resources column",
      "research_summary": {
        "total_resources": "Number of resources processed",
        "urls_found": "Number of actual URLs found",
        "citations_only": "Number with citation info but no URL"
      }
    }
  agent: resource_researcher_agent
  context:
    - process_slides_task

final_assembly_task:
  description: >
    Assemble all processed content and prepare final outputs for Coda database update.
    
    CRITICAL: You must extract the ACTUAL content from previous tasks, not placeholder descriptions.
    
    From the slide processing task, extract:
    - The actual "cleaned_slides" content
    - The actual "resources_found" list
    
    From the transcript processing task, extract:
    - The actual "transcript_srt" content (with real timestamps)
    - The actual "transcript_formatted" content (clean paragraphs)
    
    From the resource research task, extract:
    - The actual "resources_formatted" string ready for Coda
    
    Assembly requirements:
    - Combine actual slides content with resources for "Slides" column
    - Use the actual researched "resources_formatted" for "Resources" column
    - MANDATORY: Include "SRT" column with actual "transcript_srt" content (with real timestamps)
    - Use the actual "transcript_formatted" (clean paragraphs) for "Transcript" column
    - Generate processing summary for "Webhook progress" column
    - Set "Webhook status" to "Done"
    
    CRITICAL: Your JSON output MUST include all 6 columns: Slides, Resources, SRT, Transcript, Webhook progress, Webhook status
    
    DO NOT use placeholder text like "Timestamped transcript in SRT format" - use the real content from previous tasks.
    
  expected_output: >
    {
      "coda_updates": {
        "Slides": "[ACTUAL cleaned slides content from slide processing task, not placeholder text]",
        "Resources": "[ACTUAL resources_formatted string from resource research task, not placeholder text]",
        "SRT": "[MANDATORY: ACTUAL transcript_srt content with real timestamps from transcript processing task - DO NOT OMIT THIS COLUMN]", 
        "Transcript": "[ACTUAL transcript_formatted content with clean paragraphs from transcript processing task, not placeholder text]",
        "Webhook progress": "Processing summary with actual statistics",
        "Webhook status": "Done"
      },
      "processing_summary": {
        "slides_processed": "Actual number of slides processed",
        "resources_found": "Actual number of resources with URLs found",
        "transcript_length": "Actual transcript word count",
        "total_processing_time": "Actual processing time"
      }
    }
  agent: slide_processor_agent
  context:
    - process_slides_task
    - process_transcript_task  
    - research_resources_task