research_resources_task:
  description: >
    Research and find actual URLs for the speaker's PRIMARY resources - the main work they are presenting.
    This is for social media sharing (1 tweet), so focus on 1-4 most important resources only.
    
    TALK CONTEXT:
    - Speaker: {speaker}
    - Affiliation: {affiliation}  
    - Talk Title: {talk_title}
    - Slides Content: {slides_content}
    
    SMART PRIORITY ORDER (should never fail):
    
    1. QR CODES/URLs FIRST if slides available:
       * If slides content is blank/empty: skip to step 2
       * Look for any URLs/links in the slides content above
       * If URLs found: these are the speaker's intended resources, verify and use them, STOP HERE
       * If no URLs found in slides: proceed to step 2
    
    2. TITLE + SPEAKER SEARCH (most reliable):
       * Query: "{talk_title} {speaker} paper" or "{speaker} {affiliation} {talk_title}"
       * This usually finds the main paper being presented
       * ONLY include if speaker is confirmed author/co-author
       * If 1+ quality speaker-authored resource found: STOP HERE
    
    3. SOCIAL MEDIA SEARCH (posts by speaker or co-authors about their work):
       * Single query: "{talk_title}" (site:x.com OR site:linkedin.com OR site:bsky.app)
       * Look for posts/threads by speaker OR co-authors about this work
       * ONLY include if: speaker is confirmed author AND post is by one of the authors
       * If 1+ quality social media resource found: STOP HERE
    
    4. SLIDES-INFORMED SEARCH (if slides available):
       * If slides content is blank/empty: STOP HERE 
       * Extract key terms/concepts from slides content above
       * Search with speaker name + key terms from slides
       * If 1+ good resource found: STOP HERE
       * If still nothing found: return blank/empty result
    
    EFFICIENCY RULES:
    - MAX 5 searches total 
    - Stop immediately when at least 1 quality resource found  
    - QR codes/URLs from slides HIGHEST priority (speaker's intended resources)
    - Title+Speaker search most reliable fallback
    - Academic conference publications > arxiv papers > speaker's social media posts > project websites > GitHub repos
    - OK to return empty if no speaker-authored resources found - quality over quantity
    - Better empty than generic resources that aren't directly related to the talk
    
    CRITICAL VALIDATION RULES:
    - MANDATORY: Speaker "{speaker}" MUST be listed as author/co-author on ALL papers
    - MANDATORY: Verify URLs actually work before including them
    - MANDATORY: If you cannot confirm speaker authorship, DO NOT include the resource
    - Do NOT include resources just because they match the topic - they must be speaker's work
    
    STRICT EXCLUSIONS:
    - Do NOT include general speaker homepages or CV
    - Do NOT include institutional/company websites  
    - Do NOT include cited papers by other authors
    - Do NOT include comprehensive reference lists
    
    Expected result: 1-4 resources max, focus on speaker's main contributions
    
  expected_output: >
    Simple format for Coda Resources column:
    "Paper Title - https://arxiv.org/abs/123\nProject Website - https://speaker.org/project"
    
    Maximum 1-4 lines. Focus on main academic/research resources only.
    Skip GitHub unless no papers/websites found.
  agent: resource_researcher_agent

analyze_transcript_task:
  description: >
    Analyze the transcript to extract the {speaker}'s ({affiliation}) key ideas and points using their actual words and phrases.
    This analysis will be the foundation for downstream summarization and social media content generation.
    
    TRANSCRIPT CONTENT (from Coda):
    {transcript_content}
    
    SLIDES CONTEXT (for reference):
    {slides_content}
    
    CRITICAL: Use the speaker's exact words, phrases, and terminology wherever possible.
    
    Your analysis should:
    - Extract the speaker's main thesis using their own language
    - Capture key points in the speaker's voice and phrasing
    - Preserve the speaker's organizational structure and flow
    - Extract specific numbers, technical terms, and metrics exactly as stated
    - Find the most quotable/impactful statements in the speaker's words
    - Highlight surprising or counterintuitive claims using their exact phrasing
    - Capture any explicit CTAs, resource mentions, or directives from speaker
    - Extract summary/takeaway slides verbatim (perfect for social media)
    - Identify most tweetable content and social media ready quotes
    - Maintain technical accuracy while preserving authentic voice
    
  expected_output: >
    # {speaker} - {talk_title}
    
    ## Core Thesis
    [Main argument using speaker's exact words - 1-2 sentences from transcript]
    
    ## Key Points
    - [Key point 1 using speaker's phrases and terminology]
    - [Key point 2 using speaker's phrases and terminology]  
    - [Key point 3 using speaker's phrases and terminology]
    
    ## Technical Details
    [Specific numbers, methods, metrics exactly as speaker stated them]
    
    ## Notable Quotes
    > "[Most impactful quote from speaker]"
    > "[Surprising or counterintuitive claim in speaker's words]"
    > "[Technical insight worth preserving]"
    
    ## Speaker's Call-to-Action
    [Any explicit CTAs, resource mentions, or directives from speaker - use exact words]
    
    ## Social Media Ready Content
    [Most tweetable quotes, key takeaways, summary statements in speaker's voice]
    
    ## Summary/Takeaway Slides
    [If speaker has summary slides, capture them verbatim - these are perfect for social media]
    
    ## Talk Structure
    [Brief description of how speaker organized their presentation]
    
    IMPORTANT: Return ONLY the markdown content above. No additional commentary or JSON formatting.
  agent: transcript_analyzer_agent

final_assembly_task:
  description: >
    Assemble resource research and transcript analysis results for Coda database update.
    
    Extract the ACTUAL content from both completed tasks:
    - Resources: Use the resource research results for "Resources" column
    - Analysis: Use the markdown transcript analysis for "Analysis" column  
    - Generate processing summary for "Webhook progress" column
    - Set "Webhook status" to "Done"
    
    Handle cases where either task might have empty results (return blank strings, not error messages).
    
  expected_output: >
    {
      "coda_updates": {
        "Analysis": "Markdown transcript analysis from transcript task (or blank if no transcript)",
        "Webhook progress": "Analysis completed: X resources found, transcript analysis completed",
        "Webhook status": "Done"
      },
    }
  agent: resource_researcher_agent
  context:
    - analyze_transcript_task